include: package:flutter_lints/flutter.yaml

analyzer:

linter:
  rules:
    depend_on_referenced_packages: false
    overridden_fields: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    unawaited_futures: true
    always_declare_return_types: true
    avoid_void_async: true
